const { default: inquirer } = require("inquirer");

class Shape {
    constructor(text, textFill) {
        this.text = text;
        this.textFill = textFill;
    }
};

function getShape(){
    inquirer
    .prompt([
        {
            type: 'input',
            message: 'Please enter 3 letters for your logo',
            name: 'company name',
            value: ''
        },
        {
            type: 'input',
            message: 'Please enter a color for your company name',
            name: 'text fill',
            value: ''
        },
        {
            type: 'list',
            message: 'Which shape would you like for your logo?',
            name: 'shapes',
            choices: [
                {
                    name: 'square',
                    value: square
                },
                {
                    name: 'circle',
                    value: circle
                },
                {
                    name: 'triangle',
                    value: triangle
                }
            ]
        }
    ])
    .then( answers => {
        console.log(answers);
        // TODO: add line to create the SVG file containing a logo generated by data collected from user by inquirer prompts
    })
}

getShape();

module.exports = Shape;