const { default: inquirer } = require("inquirer");
const square = require('./square');
const circle = require('./circle');
const triangle = require('./triangle');
const fs = require('fs');

class Shape {
    constructor(text, textFill) {
        this.text = text;
        this.textFill = textFill;
    }
};

// function shapeify(){
//     fs.writeFile('shape.svg', userInput, (err) => 
//     err ? console.error(err) : console.log('Complete')
//     );
// }

function getShape(){
    inquirer
    .prompt([
        {
            type: 'input',
            message: 'Please enter 3 letters for your logo',
            name: 'company name',
            value: ''
        },
        {
            type: 'input',
            message: 'Please enter a color for your company name',
            name: 'text fill',
            value: ''
        },
        {
            type: 'list',
            message: 'Which shape would you like for your logo?',
            name: 'shapes',
            choices: [
                {
                    name: 'square',
                    value: squareShape
                },
                {
                    name: 'circle',
                    value: circleShape
                },
                {
                    name: 'triangle',
                    value: triangleShape
                }
            ]
        }
    ])
    .then( answers => {
        console.log(answers);
        // TODO: add line to create the SVG file containing a logo generated by data collected from user by inquirer prompts
        shapeify(X.X(answers.shape));
    })
}

getShape();

module.exports = Shape;